// <auto-generated />
using System;
using Challenge_Sprints1e2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Challenge_Sprints1e2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522025019_InitialMapping")]
    partial class InitialMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Challenge_Sprints1e2.Models.Tutor", b =>
                {
                    b.Property<int>("IdTutor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("NomeTutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_TUTOR");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdTutor");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("TB_TUTOR");
                });

            modelBuilder.Entity("Challenge_Sprints1e2.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SENHA");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("NVARCHAR2(35)")
                        .HasColumnName("TIPO_USER");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TB_USUARIO", t =>
                        {
                            t.HasCheckConstraint("CK_USUARIO_TIPO", "TIPO_USER IN ('TUTOR','VETERINARIO')");
                        });
                });

            modelBuilder.Entity("Challenge_Sprints1e2.Models.Veterinario", b =>
                {
                    b.Property<int>("IdVeterinario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("Crmv")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CRMV");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ESPECIALIDADE");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdVeterinario");

                    b.HasIndex("Crmv")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("TB_VETERINARIO");
                });

            modelBuilder.Entity("Challenge_Sprints1e2.Models.Tutor", b =>
                {
                    b.HasOne("Challenge_Sprints1e2.Models.Usuario", "Usuario")
                        .WithOne("Tutor")
                        .HasForeignKey("Challenge_Sprints1e2.Models.Tutor", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Challenge_Sprints1e2.Models.Veterinario", b =>
                {
                    b.HasOne("Challenge_Sprints1e2.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Challenge_Sprints1e2.Models.Usuario", b =>
                {
                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
